name: Read and Output hello.txt

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Step 3: Checkout the repository

      - name: Read and print hello.txt content
        run: cat hello.txt  # Step 4: Read and print content
